version: '3.3'

services:
  node-backend:
    container_name: node-backend
    image: node-backend
    depends_on:
      - postgresql-database
    build: ./server/
    env_file:
      - .env
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  postgresql-database:
    container_name: postgres-database
    image: postgres-database
    build: ./database/
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
