version: '3.3'

services:
  server:
    build: .
    image: server
    command: npm run dev
    container_name: ffaf-server
    ports:
      - "8080:8080"
    volumes:
      - .:/worker
      - /worker/node_modules
